# Generated by Django 3.2 on 2021-04-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('cameo_id', models.IntegerField()),
                ('price', models.FloatField(null=True)),
                ('currency_code', models.CharField(max_length=10)),
                ('cameo_username', models.CharField(max_length=250)),
                ('requested_user_id', models.IntegerField()),
                ('requested_user_username', models.CharField(max_length=250)),
                ('fromName', models.CharField(blank=True, max_length=500, null=True)),
                ('toName', models.CharField(max_length=500)),
                ('pronounce', models.CharField(max_length=500)),
                ('instructions', models.TextField()),
                ('occasion', models.CharField(max_length=500)),
                ('receipent', models.CharField(max_length=500)),
                ('payment_status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed')], max_length=100)),
                ('payment_method', models.CharField(choices=[('paypal', 'Paypal'), ('stripe', 'Stripe')], max_length=100)),
                ('payment_server_response', models.TextField()),
                ('order_status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed')], max_length=50)),
                ('statisfaction', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
