# Generated by Django 3.0.6 on 2021-04-17 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cameo_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='cameo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
