# Generated by Django 3.0.6 on 2021-04-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameo', '0002_auto_20210411_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameo',
            name='currency_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cameo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
