# Generated by Django 3.0.6 on 2021-04-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameo', '0003_auto_20210411_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameo',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
