# Generated by Django 3.2 on 2021-04-12 07:21

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cameo', '0005_auto_20210412_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameo',
            name='fans',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='cameo',
            name='reviews',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
