# Generated by Django 3.0.6 on 2021-04-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameo', '0006_auto_20210412_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameo',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
