# Generated by Django 3.2 on 2021-04-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameo', '0007_auto_20210417_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameo',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
