# Generated by Django 3.2.9 on 2021-12-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameo', '0008_alter_cameo_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameo',
            name='fans',
            field=models.IntegerField(default=0),
        ),
    ]
