# Generated by Django 3.2.9 on 2022-01-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameo', '0009_alter_cameo_fans'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameo',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
