# Generated by Django 3.2.9 on 2022-01-14 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameo', '0012_alter_cameo_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameo',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
