# Generated by Django 3.2 on 2021-04-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_id'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='order_id',
        ),
        migrations.AddField(
            model_name='file',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='booking.booking'),
        ),
    ]
